### ISSUE TITLE
PGO

### ISSUE THREAD

**Issue by mibere** [cosmobobak/viridithas#165]
As Rust in MSYS2 does not support PGO, I have Rust 1.79 natively installed on Windows 10 and Clang 18.1 via MSYS2.

The general compilation of Viridithas works fine and without errors. But, if someone knows how to do [PGO](https://github.com/cosmobobak/viridithas/blob/master/Makefile#L49-L53)...
If I run these commands there are dozens of warnings with _llvm-profdata_ and there is no _merged.profdata_. 

This [how-to](https://kobzol.github.io/rust/cargo/2023/07/28/rust-cargo-pgo.html) with _cargo-pgo_ and `rustup component add llvm-tools-preview` doesn't help either. Same error

```
Failed to merge PGO profile(s): warning: d:\Temp\viridithas-master\target\pgo-profiles\default_17648943948358147781_0.profraw: malformed instrumentation profile data: function name is empty
error: no profile can be merged
```

**Comment by cosmobobak** [comment]
I find that PGO on linux works perfectly when I do this:
```
$ mkdir tmp
$ cargo rustc -r --features syzygy,bindgen -- -C target-feature=+crt-static -C target-cpu=<TARGET_CPU> -C profile-generate=tmp --emit link=viridithas-profile
$ ./viridithas-profile bench
$ llvm-profdata merge -o tmp/merged.profdata tmp
$ cargo rustc -r --features syzygy,bindgen -- -C target-feature=+crt-static -C target-cpu=<TARGET_CPU> -C profile-use=tmp/merged.profdata --emit link=viridithas-pgo
```
I don't know if this is easily replicable on Windows.
