### ISSUE TITLE
Viridithas 15.0 does not work

### ISSUE THREAD

**Issue by Agu60** [cosmobobak/viridithas#209]
Hi,
I have a problem, in fritz gui, I can't install Viridithas 15.0, I get the following error message: engine could not load.
I tried to consult various forums online, but I didn't find anything that referred to my problem. Up to version 12, I had no problems. I only know that the program is written in rust. I use Windows 7. Can anyone help me? Thanks in advance.

**Comment by cosmobobak** [comment]
Happy to help - is there any more information you can provide? It would be particularly useful if the GUI has any debug info you can give me.

**Comment by Agu60** [comment]
Unfortunately, the type of error is not specified.

**Comment by Agu60** [comment]
Unfortunately, the type of error is not specified.
